#!/usr/bin/python2
# -*- coding: utf-8 -*-

"""
Copyright (C) 2015 Petteri <petteri at gmail dot com>.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see
<http://www.gnu.org/licenses/>.
"""

import os
import sys
import pipes
import xml.etree.ElementTree as ET
from urllib import unquote_plus

def usage():
    print "ls-recently-used: a wrapper for ls with files from $HOME/.local/share/recently-used.xbel as argument"
    print "ls-recently-used takes ls options (-a -l -h etc.)"
    print "Example: ls-recently-used -lath"
    sys.exit(0)

def main():
    home = os.path.expanduser("~")
    dot_path = "%s/." % home
    recent_path = "%s/.local/share/recently-used.xbel" % home
    tree = ET.parse(recent_path)
    root = tree.getroot()
    files = list()
    arguments = " ".join(sys.argv[1:])
    show_dotfiles = False

    if arguments.find("a") > 0:
        show_dotfiles = True

    if arguments.find("--help") >= 0 or \
       arguments.find("--version") >= 0:
        usage()

    for child in root:
        f = unquote_plus(child.attrib["href"][7:])
        if not os.path.exists(f):
            continue
        if show_dotfiles == False and f.find(dot_path) > -1:
            continue
        f = pipes.quote(f)
        files.append(f)

    os.system("ls --color=auto %s %s" % (arguments, " ".join(files)))

if __name__ == "__main__":
    main()
